config/routes.rb
Board10::Application.routes.draw do
  
  resources :scheduled_events

  match '/home', :to => 'home#index'
  get "home/index"
  root :to => 'home#index'
  
  resources :users
  resources :boards
  resources :members #, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :postings #, :only => [:create, :destroy]
  resources :messages
  resources :password_resets
  resources :schools
  resources :user_schools
  resources :votes

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sessions',  :to => 'sessions#new'
  










end

app/views/shared/elements/_board.html.erb
<% owner = element.members.find_by_member_type(Member::MemberType::OWNER) %>
<% if owner %>
<% user = User.find_user(owner.user_id) %>
<% end %>

<div class="posting_left_column clearfix">
<div class="inline">
	<b><%= link_to "#{strip_and_cut(element.title,26)}", element, :class => "tips link_to_text", :title => "Board: #{element.title}" %></b>
</div>
<% if user %>
<div class="inline"><%= link_to "Owner: " + strip_and_cut(user.full_name,18), user, :class => "tips link_to_text", :title => user.full_name %></div>
<% end %>
<% if element.access == Board::PRIVATE %>
<div class="inline"><i><font color="#808080"><%= element.access %></font></i></div>
<% end %>
<div class="inline">
(<%= pluralize(element.view_count, views_str) + ', ' + pluralize(element.postings.count, 'post') %>)
</div>
<% if !element.active? %>
<div class="inline"><i>(This board is inactive)</i></div>
<% end %>
</div>

<div class="posting_right_column clearfix">
<div class="inline"><%= strip_and_cut(element.description, 300) %></div>

<% if user %>
	<% # not a good thing, but I have to do that for the sake of simplicity
	message_subj = "Join request for board \"#{element.title}\"" 
	%>
<div class="posting_actions">	
	<% if element.active? && !current_user.member?(element) && !user.recieved.join_requests.unread.where("from_user = ? and subject = ?", current_user.id, message_subj).any? %>
		<div class="action_btn inline">
		<%= form_for current_user.sent.build(:from_user => current_user.id), :class => "submitable", :remote => true do |f| %>
		  <%= f.hidden_field :to_user, :value => owner.user_id %>
		  <%= f.hidden_field :board_id, :value => element.id %>
		  <%= f.hidden_field :search, :value => params[:search] %>
		  <div class="field">
		  <%= f.text_area :content, :rows => 4, :cols => 33, :value => "Hi!\nI would like to join your board.\nThank you!" %>
		  </div>
		  <%= f.submit "#{Message::Commit::JOIN}", :class => "button_confirm tips", :disable_with => "Sending...", :title => "Join is a request to become a member of the board.\nAfter owner's confirmation your profile will be linked to the board. You will be able to see private posts and write on this board." %>
		<% end %>
		</div>
	<% end %>
	<% if element.active? && !current_user.follower?(element) %>
	<div class="action_btn float_right">
	<%= form_for current_user.members.build(:board_id => element.id), :class => "submitable", :remote => true do |f| %>
	<%= f.hidden_field :board_id %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :search, :value => params[:search] %>
	<%= f.submit "#{Member::Commit::FOLLOW}", :class => "button_neutral tips", :disable_with => "Processing...", :title => "Follow will allow you to recieve only public posts from this board. You do not need owner's permission to follow a board, but you will not be able to post on the private boards." %>
	<% end %>
	</div>
<% end %>
</div>
<% end %>

</div>

<% if admin? %>
<div class="action_btn float_right">
<%= link_to 'Edit', edit_board_path(element), :class => "edit_button" %>
<%= link_to 'Delete', element, confirm: 'Are you sure?', method: :delete, :disable_with => "Deleting...", :class => "delete_button" %>
</div>
<% end %>

app/views/shared/elements/_element.html.erb
<% return nil if element.nil? %>
<div class="<%= element.class_type %>_element clearfix">
<%= render "shared/elements/#{element.class_type}", :element => element, :read_only => read_only %>
</div> <!-- cl-el -->


app/views/shared/elements/_member.html.erb
<% board = Board.find_board(element.board_id) %>
<% return nil if board.nil? %>
<div class="inline"><%= board.access %></div>
<div class="inline">Board: <%= link_to board.title, board %></div>
<div class="inline"><%= board.status unless ( board.active ) %></div>
<div class="inline">
	(<%= pluralize(board.view_count, views_str) + ', ' + pluralize(board.postings.count, 'post') %>)
</div>
<br class="clearBoth" />
<div class="inline"><%= strip_and_cut( board.description ) %></div>

app/views/shared/elements/_message.html.erb
<% from_user = User.find_user( element.from_user )%>
<div class="float_right">
<%= button_to 'x', element, :class => "button_reject", confirm: "Do you want to remove this message?", method: :delete, :remote => true %>
<%= render 'messages/confirm_reject', :message => element, :from => from_user %>
</div>

<% if from_user %>
	<% if element.msg_state == Message::State::UNREAD %>
	<div class="message_from"><b><%= link_to from_user.full_name, from_user %></b></div>
	<div class="message_subj"><b><%= link_to strip_and_cut(element.subject, 70), element %></b></div>
	<% else %> 
	<div class="message_from"><%= link_to from_user.full_name, from_user %></div>
	<div class="message_subj"><%= link_to strip_and_cut(element.subject, 70), element %></div>
	<% end %>
<% else %>
	<div class="inline"><b>This user account has been deactivated</b></div>
<% end %>

app/views/shared/elements/_posting.html.erb
<% if element.scheduled_event_id %>
<div class="event">
<% end %>
<div class="posting_left_column clearfix">
    <div class="inline">        
        <% if element.active_user %>
            <% if current_user && current_user.id == element.user_id %>
            posted by me
            <% elsif user = User.find_user(element.user_id) %>
                <% if current_user %>
                <b><%= link_to "#{user.full_name}", user_path(element.user_id), :class => "link_to_text" %></b>
                <% else %>
                <%= user.full_name %>
                <% end %>
            <% else %>Unknown user<% end %>
        <% else %>Unknown user<% end %>
    </div>
        
    <% unless element.created_at.nil? %>
        <div class="inline tips" title="<%= (time_ago_in_words(element.created_at)+" ago") %>">
            <%= element.created_at.getlocal.strftime("%m/%d/%Y %I:%M%p") %><br />
        </div>
    <% end %>
  
    <div class="inline clickable">
    	<% board = Board.find_board(element.board_id) %>
        <% if board %>
          <% if current_user && stored_location_or_home =~ /\/home?/ %>
        <b><%= link_to "#{strip_and_cut(board.title,26)}", home_path + "?board=#{element.board_id}", :class => "tips link_to_text", :title => "Board: #{board.title}", :disable_with => "Loading board..." %></b>
          <% else %>
        <b><%= strip_and_cut(board.title,26) %></b>
          <% end %>
        <% else %>
        <i>(Board was deactivated)</i>
        <% end %>
    </div>

    <% if board && !board.school_id.nil? %>
    <% school = School.find_school(board.school_id) %>
    <div class="inline clickable">
        <% if current_user && stored_location_or_home =~ /\/home?/ %>
        <b><%= link_to "#{strip_and_cut(school.name,26)}", home_path + "?school=#{school.id}", :class => "tips link_to_text", :title => "#{school_desc(school)}", :disable_with => "Loading school..." %></b>
        <% else %>
        <b><%= strip_and_cut(school.name,26) %></b>
        <% end %>
    </div>
    <% end %>
</div>

<div class="posting_right_column clearfix">
    <% if element.scheduled_event_id %>
    <% if event = ScheduledEvent.find_event(element.scheduled_event_id) %>
      <%= link_to event.description.html_safe, posting_path(element), :class => "inline subject" %>
    <% end %>
    <% end %>
    
    <% if !element.subject.nil? && !element.subject.empty? %>
    <%= link_to strip_and_cut(element.subject,50), posting_path(element), :class => "inline subject" %>
    <% end %>
    <div class="inline">
    <%= link_to strip_and_cut(element.content, 150), posting_path(element), :class => "link_to_text" %>
    </div>
    <% unless element.view_count == 0 %>
    <div class="inline">(<%= pluralize( element.view_count, 'UP')  %>)</div>
    <% end %>
    <% if element.access == Posting::PRIVATE %>
    <div class="inline"><i><font color="#808080"><%= element.access %></font></i></div>
    <% end %>
</div>

<div class="posting_actions">
	<% if !read_only && current_user && current_user.id != element.user_id %>
	<div class="action_btn float_right">
    <%= render 'votes/vote_btn', :element => element %>
    </div>
    <% end %>
	<% if !read_only && current_user && current_user.id == element.user_id %>
	<div class="action_btn float_right">
	<%= button_to 'delete', element, confirm: 'Are you sure?',
            :remote => true, :disable_with => 'delete',
            method: :delete, :class => "delete_button",
            :title => 'Delete post'
	%>
	</div>
	<div class="action_btn float_right">
	<%= link_to 'edit', edit_posting_path(element), :class => "edit_button", :title => "Edit post", :disable_with => "edit" %>
	</div>
	<% elsif current_user && current_user.id != element.user_id %>
	<div class="action_btn float_right">
	<%= link_to 'reply', posting_path(element), :class => "button_neutral", :disable_with => "reply" %>
	</div>
	<% end %>
</div>

<% if element.scheduled_event_id %>
</div> <!-- event -->
<% end %>

app/views/shared/elements/_school.html.erb
<div class="float_right">
<%= render 'user_schools/btn_add_school', :school => element %>
</div>
<div class="float_left">
	<b><%= link_to strip_and_cut(element.school_name,45), element.url, :confirm => "You will be redirected to the #{element.name} website\n(#{element.url}).\nAre you sure?", :class => "tips", :title => "#{element.school_name}" %></b>
</div>
<br />
<div class="float_left"><%= element.location %></div>



app/views/shared/elements/_small_board.html.erb
<div class="inline"><%= link_to element.title, element %></div>
<div class="inline"><%= element.description %></div>
<% if !element.active? %>
<div class="inline"><i>(This board is inactive)</i></div>
<% end %>
<% owner = element.members.find_by_member_type(Member::MemberType::OWNER) %>
<% if owner %>
<% user = User.find_user(owner.user_id) %>
<% end %>
<% if user %>
	<div class="inline">(Owner: <%= user.full_name %>)</div>
	<% # not a good thing, but I have to do that for the sake of simplicity
	message_subj = "Join request for board \"#{element.title}\"" 
	%>
	<% if element.active? && !current_user.member?(element) && !user.recieved.join_requests.unread.where("from_user = ? and subject = ?", current_user.id, message_subj).any? %>
	<div class="inline_right">
	<%= form_for current_user.sent.build(:from_user => current_user.id), :class => "submitable", :remote => true do |f| %>
	  <%= f.hidden_field :to_user, :value => owner.user_id %>
	  <%= f.hidden_field :board_id, :value => element.id %>
	  <%= f.text_field :content, :size => 40, :value => "Hi! I would like to join your board. Thank you!" %>
	  <%= f.submit "#{Message::Commit::JOIN}", :class => "button_confirm tips", :title => "Join is a request to become a member of the board.\nAfter owner's confirmation your profile will be linked to the board. You will be able to see private posts and write on that board." %>
	<% end %>
	</div>
	<% end %>
	<% if element.active? && !current_user.follower?(element) %>
	<div class="inline_right">
	<%= form_for current_user.members.build(:board_id => element.id), :class => "submitable", :remote => true do |f| %>
	  
	  <%= f.hidden_field :board_id %>
	  <%= f.hidden_field :user_id, :value => current_user.id %>
	  <%= f.hidden_field :search, :value => params[:search] %>
	  <%= f.submit "#{Member::Commit::FOLLOW}", :class => "button_neutral tips", :title => "Follow will allow you to recieve only public posts from this board. You do not need owner's permission to follow a board, but you will not be able to post on the private boards." %>
	<% end %>
	</div>
	<% end %>
<% end %>
<br class="clearBoth" />

app/views/shared/elements/_small_element.html.erb
<% return nil if element.nil? %>

<div class="small_element">
<%= render "shared/elements/small_#{element.class_type}", :element => element, :action => action, :read_only => read_only %>
</div> <!-- cl-el -->

app/views/shared/elements/_small_member.html.erb
<% user = User.find_user(element.user_id) %>
<% return nil if user.nil? %>

<% owner = user.owner?(@board) %>
<% member = user.member?(@board) unless owner %>
<% if @board.active? %>
<div class="link_with_btn">
<div class="link_btn">
<% if action == 'invite' %>
	<%= form_for current_user.sent.build(:from_user => current_user.id), :class => "submitable", :remote => true do |f| %>
	  <%= f.hidden_field :board_id, :value => @board.id %>
	  <%= f.hidden_field :to_user, :value => user.id %>
	  <%= f.text_field :content, :value => "Hi! I would like to invite you to my board. Thank you!" %>
	  <%= f.submit "#{Message::Commit::INVITE}", :class => "button_confirm" %>
	<% end %>
<% elsif action == 'ban' %>
	<% if member %>
	<%= button_to 'x', @board.members.find_by_user_id(user.id),
         confirm: "Do you want to ban #{user.full_name}?", 
         :class => "button_reject tips", :disable_with => 'x...',
         method: :delete, :remote => true,
         :title => "Ban #{user.full_name}" %>
	<% end %>

<% end %>
</div>
<% if owner %>
<div class="inline"><%= link_to user.full_name, user %> (Owner)</div>
<% elsif member %>
<div class="inline"><%= link_to user.full_name, user %> (Member)</div>
<% else %>
<div class="inline"><%= link_to user.full_name, user %> (Follower)</div>
<% end %>
</div>
<% else %>
<% if owner %>
<div class="inline"><%= link_to user.full_name, user %> (Owenr)</div>
<% elsif member %>
<div class="inline"><%= link_to user.full_name, user %> (Member)</div>
<% else %>
<div class="inline"><%= link_to user.full_name, user %> (Follower)</div>
<% end %>
<% end %>
<br class="clearBoth" />

app/views/shared/elements/_small_posting.html.erb
<div class="posting_left_column clearfix">
    <% if !element.subject.nil? && !element.subject.empty? %>
    <div class="inline subject"><%= ( strip_and_cut(element.subject,120) ) %></div>
    <% end %>

    <div class="inline">        
        <% if element.active_user %>
            <% if current_user && current_user.id == element.user_id %>
            posted by me
            <% elsif user = element.user %>
                <%= link_to "#{user.full_name}", user_path(element.user_id) %>
            <% else %>Unknown user<% end %>
        <% else %>Unknown user<% end %>
    </div>
        
    <% unless element.created_at.nil? %>
        <div class="inline"><%= (time_ago_in_words(element.created_at)+" ago") %></div>
    <% end %>
  
    <div class="inline">
        <% if board = Board.find_board(element.board_id) %>
        <%= link_to "#{strip_and_cut(board.title,30)}", board_path(element.board_id), :class => "link_to_text" %>
        <% else %>
        <i>(Board was removed)</i>
        <% end %>
    </div>

    <% if !board.nil? && !board.school_id.nil? %>
    <% school = School.find_school(board.school_id) %>
    <div class="inline">
    	<%= link_to "#{strip_and_cut(school.name,30)}", school_path(school.id), :class => "link_to_text" %>
    	</div>
    <% end %>
</div>

<div class="posting_right_column clearfix">
	<% if (!read_only && current_user && current_user.id == element.user_id) || (current_user && admin?) %>
	<div class="hidable">
	<%= link_to 'Edit', edit_posting_path(element), :class => "edit_button" %>
	<%= button_to 'Delete', element, confirm: 'Are you sure?',
	    :remote => true, :disable_with => 'Deleting...',
	    method: :delete, :class => "button_neutral"
	%>
	</div>
	<% end %>
    <div class="inline">
    <%= link_to strip_and_cut(element.content, 300), posting_path(element), :class => "link_to_text" %>
    </div>
    <% unless element.view_count == 0 %>
    <div class="inline">(<%= pluralize( element.view_count, views_str)  %>)</div>
    <% end %>
    <% if element.access == Posting::PRIVATE %>
    <div class="inline"><i><font color="#808080"><%= element.access %></font></i></div>
    <% end %>
</div>
<br class="clearBoth" />

app/views/shared/elements/_small_school.html.erb
<div class="inline"><%= link_to element.school_name, element.url %></div>
<div class="inline"><%= element.location %></div>
<div class="inline_right"><%= render 'home/btn_add_school', :school => element %></div>
<br class="clearBoth" />

app/views/shared/elements/_small_user.html.erb
<div class="inline"><%= link_to element.full_name, element %></div>
<% if !element.member?(@board) %>
<div class="inline_right">
<%= form_for current_user.sent.build(:from_user => current_user.id), :class => "submitable", :remote => true do |f| %>
  <%= f.hidden_field :board_id, :value => @board.id %>
  <%= f.hidden_field :to_user, :value => element.id %>
  <%= f.text_field :content, :value => "Hi! I would like to invite you to my board. Thank you!" %>
  <%= f.submit "#{Message::Commit::INVITE}", :class => "button_confirm" %>
<% end %>	
</div>
<% end %>
<br class="clearBoth" />

app/views/shared/elements/_small_vote.html.erb
<% obj = Vote.object_by_vote element %>
<% return nil if obj.nil? %>
<% if obj.title == "Private Post" %>
Private Post<br />
<% else %>
<%= link_to strip_and_cut(obj.title, 50), obj %><br />
<% end %>
<%= strip_and_cut(obj.description, 30) %> <i>(<%= pluralize(obj.view_count,views_str) %>)</i><br />

app/views/shared/elements/_user.html.erb
<div class="hidable float_right">
<% if admin?  %>
<%= link_to 'Edit', edit_user_path(element), :class => "edit_button" %>
<%= link_to 'Delete', element, confirm: 'Are you sure?', method: :delete,
	:title => "Delete #{element.full_name}", :class => "delete_button tips" %>
<% end %>
</div>

<div class="posting_left_column clearfix">
<div class="inline"><%= link_to element.full_name, element %></div>
<div class="inline"><%= pluralize( element.view_count, views_str ) %></div>
<div class="inline"><%= element.location %></div>
</div>

<div class="posting_right_column clearfix">
<% if @board && !element.member?(@board) %>
<div class="inline_right">
<%= form_for current_user.sent.build(:from_user => current_user.id), :class => "submitable", :remote => true do |f| %>
  <%= f.hidden_field :board_id, :value => @board.id %>
  <%= f.hidden_field :to_user, :value => element.id %>
  <%= f.text_area :content, :rows => 4, :cols => 33, :value => "Hi!\nI would like to invite you to this board.\nThank you!" %>
  <%= f.submit "#{Message::Commit::INVITE}", :class => "button_confirm" %>
<% end %>	
</div>
<% end %>
</div>