config/routes.rb
Board10::Application.routes.draw do
  
  resources :scheduled_events

  match '/home', :to => 'home#index'
  get "home/index"
  root :to => 'home#index'
  
  resources :users
  resources :boards
  resources :members #, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :postings #, :only => [:create, :destroy]
  resources :messages
  resources :password_resets
  resources :schools
  resources :user_schools
  resources :votes

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sessions',  :to => 'sessions#new'
  










end

app/models/scheduled_event.rb
class ScheduledEvent < ActiveRecord::Base
  attr_accessible :start_date, :end_date, :start_time, :end_time, :repeat, :mo,
                  :tu, :we, :th, :fr, :sa, :su, :month, :month_day, :month_end
  
  belongs_to :posting, :class_name => "Posting"
  
  class Repeat
    DAILY = 0
    WEEKLY = 1
    BIWEEKLY = 2
    MONTHLY = 3
    YEARLY = 4
  end
  
  def description
    desc = ""
    if repeat == ScheduledEvent::Repeat::DAILY
      if start_date == end_date
        desc = "Event on #{start_date.strftime("%m/%d/%Y")}:<br />"
      else
        desc = "Daily Event (#{start_date.strftime("%m/%d/%Y")} - #{end_date.strftime("%m/%d/%Y")}):<br />"
      end
      desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p")
    elsif repeat == ScheduledEvent::Repeat::WEEKLY
      if start_date == end_date
        desc = "This week event on " + week_days + "<br />"
        desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p")
      else
        desc = "Weekly Event (#{start_date.strftime("%m/%d/%Y")} - #{end_date.strftime("%m/%d/%Y")}):<br />"
        desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p") + " on " + week_days
      end
      
    elsif repeat == ScheduledEvent::Repeat::BIWEEKLY
      if start_date == end_date
        desc = "This week event on " + week_days + "<br />"
        desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p")
      else
        desc = "Biweekly Event (#{start_date.strftime("%m/%d/%Y")} - #{end_date.strftime("%m/%d/%Y")}):<br />"
        desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p") + " on " + week_days
      end
    elsif repeat == ScheduledEvent::Repeat::MONTHLY
      if start_date == end_date
        desc = "Event on #{start_date.strftime("%m/%d/%Y")}:<br />"
      else
        desc = "Monthly Event (#{start_date.strftime("%m/%d/%Y")} - #{end_date.strftime("%m/%d/%Y")}):<br />"
      end
      desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p")
      if start_date != end_date && month_end
        desc += " on every month end"
      elsif start_date != end_date
        desc += " on " + month_day.ordinalize + " every month"
      end
    elsif repeat == ScheduledEvent::Repeat::YEARLY
      if start_date == end_date
        desc = "Event on #{start_date.strftime("%m/%d/%Y")}:<br />"
      else
        desc = "Yearly Event (#{start_date.strftime("%m/%d/%Y")} - #{end_date.strftime("%m/%d/%Y")}):<br />"
      end
      desc += "From " + start_time.strftime("%I:%M%p") +
           " to " + end_time.strftime("%I:%M%p")
      if month_end && start_date != end_date
        desc += " every month end"
      elsif start_date != end_date
        desc += " on " + Date::MONTHNAMES[month] + " " + month_day.ordinalize + " every year"
      end
    end
    desc
  end
  
  def week_days
    days =""
    days += "Monday " if mo
    days += "Tuesday " if tu
    days += "Wednesday " if we
    days += "Thursday " if th
    days += "Friday " if fr
    days += "Saturday " if sa
    days += "Sunday " if su
    days
  end
  
  def self.find_event event_id
    event = @cache[event_id]
    return event if event
    event = self.find(event_id)
    @cache[event_id] = event
    event
    rescue ActiveRecord::RecordNotFound
     nil
  end
  
  def get_first_event_date start
    return nil if start.nil? || start > end_date
    if ( repeat == ScheduledEvent::Repeat::MONTHLY ||
       repeat == ScheduledEvent::Repeat::YEARLY )
      if start >= start_date && start.beginning_of_month == start_date.beginning_of_month
        return Date.new(start.year, start.month, month_day)
      elsif start.beginning_of_month < start_date.beginning_of_month
        return nil
      end
    elsif start < start_date
      return nil
    end
    if new_record?
      # correct start_date if it is in the past:
      today = Date.today
      start_date = today if start < today
    end
    if repeat == ScheduledEvent::Repeat::DAILY
      next_event = start
    elsif repeat == ScheduledEvent::Repeat::WEEKLY || repeat == ScheduledEvent::Repeat::BIWEEKLY
      next_event = next_week_date start
    elsif repeat == ScheduledEvent::Repeat::MONTHLY
      next_event = find_next_date_for_monthly(start)
    elsif repeat == ScheduledEvent::Repeat::YEARLY
      next_event = find_next_date_for_yearly(start)
    end
    next_event
  end
  
  def get_next_event_date start
    get_first_event_date(start+1.day)
  end
  
  def next_week_date start
    wday = start.wday
    while !wdays[wday] do
      wday = ( wday == 6 ? 0 : wday + 1 )
      start += 1.day
    end 
    start
  end

  def wday_match? start
    wdays[start.wday]
  end
    
  def wdays
    @wdays_hash ||= {0 => su, 1 => mo, 2 => tu, 3 => we, 4 => th, 5 => fr, 6 => sa}
  end
  
  def future_month_events start
    return nil if start.nil? || start > end_date
    current_month = start.month
    # get_first_event_date will return nil if we are after end_date
    curr_event = get_first_event_date start
    events = []
    if repeat == Repeat::MONTHLY || repeat == Repeat::YEARLY
      events.push clone_scheduled_event(curr_event) if curr_event
      return events
    end
    if curr_event && curr_event.month == current_month
      events.push clone_scheduled_event(curr_event)
    end
    curr_event = start if curr_event.nil?
    while current_month == curr_event.month do
      tmp_date = get_next_event_date(curr_event)
      if tmp_date && tmp_date != curr_event && tmp_date <= end_date
        events.push clone_scheduled_event(tmp_date)
        curr_event = tmp_date
      else
        curr_event += 1.day
      end
    end
    events
  end
  
  def clone_scheduled_event next_date
    return nil if next_date.nil?
    new_event = dup
    new_event.next_event = next_date
    new_event
  end
  
  # this method will return the next event after the start
  def find_next_date_for_monthly start
    if month_end || (start.month == 2 && month_day > 28) || month_day > 30
      next_date = start.end_of_month
    else
      next_date = Date.new(start.year, start.month, month_day)
    end
    return next_date if next_date <= end_date
    #next_date = next_date + 1.month
    #next_date = next_date.end_of_month if month_end
    nil
  end
  
  # this method will return the next event after the start
  def find_next_date_for_yearly start
    if (month == start.month && month_end) || 
      (month == start.month && start.month == 2 && month_day > 28) ||
      (month == start.month && month_day > 30)
      return start.end_of_month
    elsif month == start.month
      next_date = Date.new(start.year, month, month_day)
    end
    return next_date if next_date && next_date <= end_date
    #unless next_date.future?
    #  next_date = next_date + 1.year
    #  next_date = next_date.end_of_month if month_end
    #end
    #next_date
    nil
  end
  
  def validate_event
    errors = ""
    errors += "Event start date can not be blank<br />" unless start_date
    errors += "Event end date can not be blank<br />" unless end_date
    errors += "Event start time can not be blank<br />" unless start_time
    errors += "Event end time can not be blank<br />" unless end_time
    errors += "Please select type of event: daily, weekly, etc.<br />" unless repeat
    errors += "Event start date #{start_date} can not be after event end date #{end_date}<br />" unless end_date >= start_date
    #errors += "Event start time can not be after or the same as event end time<br />" unless end_time > start_time
    
    case repeat
    when ScheduledEvent::Repeat::DAILY
    when ScheduledEvent::Repeat::WEEKLY
      unless mo || tu || we || th || fr || sa || su
        errors += "At least one of the weekdays must be specifaied for a weekly event.<br />"
      end
    when ScheduledEvent::Repeat::BIWEEKLY
      unless mo || tu || we || th || fr || sa || su
        errors += "At least one of the weekdays must be specifaied for a biweekly event.<br />"
      end
    when ScheduledEvent::Repeat::MONTHLY
      if month_end.nil? && month_day.nil?
        errors += "For monthly event a month day or the month end has to be specified.<br />"
      end
    when ScheduledEvent::Repeat::YEARLY
      if month_end.nil? && month.nil?
        errors += "For yearly event month can't be blank.<br />"
      end
      if month_end.nil? && month_day.nil? #params[:date][:day] 
        errors += "For yearly event a month day or the month end has to be specified.<br />"
      end
    else
      errors += "Unknown event type.<br />"
    end
    errors
  end
  
  private
  @cache = Hash.new
  REPEAT_TYPE = { 0 => "Daily", 1 => "Weekly", 2 => "Biweekly", 3 => "Monthly", 4 => "Yearly" }
end

app/controllers/scheduled_events_controller.rb
class ScheduledEventsController < ApplicationController
  include PostingsHelper
  include ApplicationHelper
  before_filter :authenticate, :only => [:create]
  before_filter :owner_user, :only => [:update, :destroy]
  before_filter :admin_user, :only => [:index, :new, :edit, :show]
  # GET /scheduled_events
  # GET /scheduled_events.json
  def index
    @scheduled_events = ScheduledEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scheduled_events }
    end
  end

  # GET /scheduled_events/1
  # GET /scheduled_events/1.json
  def show
    @scheduled_event = ScheduledEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scheduled_event }
    end
  end

  # GET /scheduled_events/new
  # GET /scheduled_events/new.json
  def new
    @scheduled_event = ScheduledEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scheduled_event }
    end
  end

  # GET /scheduled_events/1/edit
  def edit
    @scheduled_event = ScheduledEvent.find(params[:id])
  end

  # POST /scheduled_events
  # POST /scheduled_events.json
  def create
    @scheduled_event = ScheduledEvent.new(params[:scheduled_event])

    respond_to do |format|
      if @scheduled_event.save
        format.html { redirect_to @scheduled_event, notice: 'Scheduled event was successfully created.' }
        format.json { render json: @scheduled_event, status: :created, location: @scheduled_event }
      else
        format.html { render action: "new" }
        format.json { render json: @scheduled_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scheduled_events/1
  # PUT /scheduled_events/1.json
  def update
    @scheduled_event = ScheduledEvent.find(params[:id])

    respond_to do |format|
      if @scheduled_event.update_attributes(params[:scheduled_event])
        format.html { redirect_to @scheduled_event, notice: 'Scheduled event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @scheduled_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_events/1
  # DELETE /scheduled_events/1.json
  def destroy
    @scheduled_event = ScheduledEvent.find(params[:id])
    @scheduled_event.destroy

    respond_to do |format|
      format.html { redirect_to scheduled_events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/scheduled_events_helper.rb
module ScheduledEventsHelper
end

app/views/scheduled_events/_form.html.erb
<%= form_for(@scheduled_event) do |f| %>
  <% if @scheduled_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled_event.errors.count, "error") %> prohibited this scheduled_event from being saved:</h2>

      <ul>
      <% @scheduled_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :next_event_date %><%= f.date_select :next_event_date %>
  </div>
  <div class="field">
    <%= f.label :next_event_time %><%= f.time_select :next_event_time %>
  </div>
  <div class="field">
    <%= f.label :start_date %><%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :repeat %><%= f.number_field :repeat %>
  </div>
  <div class="field">
    <%= f.label :mo %><%= f.check_box :mo %>
    <%= f.label :tu %><%= f.check_box :tu %>
    <%= f.label :we %><%= f.check_box :we %>
    <%= f.label :th %><%= f.check_box :th %>
    <%= f.label :fr %><%= f.check_box :fr %>
    <%= f.label :sa %><%= f.check_box :sa %>
    <%= f.label :su %><%= f.check_box :su %>
  </div>
  <div class="field">
    <%= f.label :month_end %><%= f.check_box :month_end %>
  </div>
  <div class="field">
    <%= f.label :month %><%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :month_day %><%= f.number_field :month_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scheduled_events/_form_fields_for.html.erb
    <%= f.fields_for :scheduled_event do |builder| %>
      <%= builder.label :start_date, :class => 'tips', :title => "On what date are you planning to start?" %>
      <%= builder.date_select :start_date, :start_year => Date.today.year, :add_month_numbers => true, :end_year => Time.now.year + 10 %><br />
      <%= builder.label :end_date, :class => 'tips', :title => "On what date are you planning to stop your events?" %>
      <%= builder.date_select :end_date, :start_year => Date.today.year, :add_month_numbers => true, :end_year => Time.now.year + 10 %><br />
      <%= builder.label :from, :class => 'tips', :title => "At what time your event starts?" %> 
      <%= builder.time_select :start_time, {:default => Time.now.getlocal, :minute_step => 5, :ampm => true } %>
      <%= builder.label :to, :class => 'tips', :title => "At what time your event ends?" %> 
      <%= builder.time_select :end_time, {:default => Time.now.getlocal, :minute_step => 5, :ampm => true} %><br />
      <%= builder.radio_button 'repeat', '0', :checked => ( posting && posting.scheduled_event.repeat == 0 ? true : true ) %>
        <%= builder.label :daily , "Daily", :class => 'tips', :title => "Is it a daily event?" %><br />
      <%= builder.radio_button 'repeat', '1', :checked => ( posting && posting.scheduled_event.repeat == 1 ? true : false ) %>
        <%= builder.label :weekly , "Weekly", :class => 'tips', :title => "For weekly events please specify week days." %> on
      <%= builder.check_box :mo %><%= builder.label :mo %>
      <%= builder.check_box :tu %><%= builder.label :tu %>
      <%= builder.check_box :we %><%= builder.label :we %>
      <%= builder.check_box :th %><%= builder.label :th %>
      <%= builder.check_box :fr %><%= builder.label :fr %>
      <%= builder.check_box :sa %><%= builder.label :sa %>
      <%= builder.check_box :su %><%= builder.label :su %><br />
      <%= builder.radio_button 'repeat', '3', :checked => ( posting && posting.scheduled_event.repeat == 3 ? true : false ) %>
        <%= builder.label :monthly , "Monthly", :class => 'tips', :title => "For monthly event you have two options: event on the month end or on a particular day of the month." %> or 
      <%= builder.radio_button 'repeat', '4', :checked => ( posting && posting.scheduled_event.repeat == 4 ? true : false ) %>
        <%= builder.label :yearly , "Yearly", :class => 'tips', :title => "For yearly events please specify the month in the year and whether it is on the month end or on some particular day." %> in <%= select_month Date.today %><br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        On <%= builder.label :month_end, :class => 'tips', :title => "Is your event on a month end?" %>?
        <%= builder.check_box :month_end %> or select a day <%= select_day Date.today %><br />
    <% end %>

app/views/scheduled_events/edit.html.erb
<h1>Editing scheduled_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_event %> |
<%= link_to 'Back', scheduled_events_path %>

app/views/scheduled_events/index.html.erb
<h1>Listing scheduled_events</h1>

<table>
  <tr>
    <th>Next event date</th>
    <th>Next event time</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Repeat</th>
    <th>Mo</th>
    <th>Tu</th>
    <th>We</th>
    <th>Th</th>
    <th>Fr</th>
    <th>Sa</th>
    <th>Su</th>
    <th>Month end</th>
    <th>Month</th>
    <th>Month day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scheduled_events.each do |scheduled_event| %>
  <tr>
    <td><%= scheduled_event.next_event_date %></td>
    <td><%= scheduled_event.next_event_time %></td>
    <td><%= scheduled_event.start_date %></td>
    <td><%= scheduled_event.end_date %></td>
    <td><%= scheduled_event.start_time %></td>
    <td><%= scheduled_event.end_time %></td>
    <td><%= scheduled_event.repeat %></td>
    <td><%= scheduled_event.mo %></td>
    <td><%= scheduled_event.tu %></td>
    <td><%= scheduled_event.we %></td>
    <td><%= scheduled_event.th %></td>
    <td><%= scheduled_event.fr %></td>
    <td><%= scheduled_event.sa %></td>
    <td><%= scheduled_event.su %></td>
    <td><%= scheduled_event.month_end %></td>
    <td><%= scheduled_event.month %></td>
    <td><%= scheduled_event.month_day %></td>
    <td><%= link_to 'Show', scheduled_event %></td>
    <td><%= link_to 'Edit', edit_scheduled_event_path(scheduled_event) %></td>
    <td><%= link_to 'Destroy', scheduled_event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scheduled event', new_scheduled_event_path %>

app/views/scheduled_events/new.html.erb
<h1>New scheduled_event</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_events_path %>

app/views/scheduled_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Next event date:</b>
  <%= @scheduled_event.next_event_date %>
</p>

<p>
  <b>Next event time:</b>
  <%= @scheduled_event.next_event_time %>
</p>

<p>
  <b>Start date:</b>
  <%= @scheduled_event.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @scheduled_event.end_date %>
</p>

<p>
  <b>Start time:</b>
  <%= @scheduled_event.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @scheduled_event.end_time %>
</p>

<p>
  <b>Repeat:</b>
  <%= @scheduled_event.repeat %>
</p>

<p>
  <b>Mo:</b>
  <%= @scheduled_event.mo %>
</p>

<p>
  <b>Tu:</b>
  <%= @scheduled_event.tu %>
</p>

<p>
  <b>We:</b>
  <%= @scheduled_event.we %>
</p>

<p>
  <b>Th:</b>
  <%= @scheduled_event.th %>
</p>

<p>
  <b>Fr:</b>
  <%= @scheduled_event.fr %>
</p>

<p>
  <b>Sa:</b>
  <%= @scheduled_event.sa %>
</p>

<p>
  <b>Su:</b>
  <%= @scheduled_event.su %>
</p>

<p>
  <b>Month end:</b>
  <%= @scheduled_event.month_end %>
</p>

<p>
  <b>Month:</b>
  <%= @scheduled_event.month %>
</p>

<p>
  <b>Month day:</b>
  <%= @scheduled_event.month_day %>
</p>


<%= link_to 'Edit', edit_scheduled_event_path(@scheduled_event) %> |
<%= link_to 'Back', scheduled_events_path %>