config/routes.rb
Board10::Application.routes.draw do
  
  resources :scheduled_events

  match '/home', :to => 'home#index'
  get "home/index"
  root :to => 'home#index'
  
  resources :users
  resources :boards
  resources :members #, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :postings #, :only => [:create, :destroy]
  resources :messages
  resources :password_resets
  resources :schools
  resources :user_schools
  resources :votes

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sessions',  :to => 'sessions#new'
  










end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :users, :foreign_key => "school_id", :class_name => "User"
  has_many :boards, :foreign_key => "school_id", :class_name => "Board"
  has_many :postings, :through => :boards
  has_many :scheduled_events, :through => :boards
  
  validates :state, :presence => true, :length   => { :maximum => 2 }
  validates :city, :presence => true, :length   => { :maximum => 150 }
  validates :name, :presence => true
  
  #default_scope :order => 'name ASC'
  
  def self.find_school school_id
    school = @cache[school_id]
    return school if school
    school = self.find(school_id)
    @cache[school_id] = school
    school
    rescue ActiveRecord::RecordNotFound
     nil
  end
  
  def self.search(search, state = nil, city = nil)
    
    if search || state || city
      tmp = nil
      tmp = search.sub(' ', '%') unless search.nil?
      if state && !state.blank?
        where('state = ? and city like ? and CONCAT( name, \' \', name ) LIKE ?', "#{state}", "%#{city}%", "%#{tmp}%").order(:name)
      else
        where('city like ? and CONCAT( name, \' \', name ) LIKE ?', "%#{city}%", "%#{tmp}%").order(:name)
      end
    else
      scoped.order(:name) # the same as all, but does not perform the actual query
    end
  end
  
  def class_type
    'school'
  end
  
  def title
    school_name
  end
  
  def school_name
    name
  end
  
  def location
    State.long_name(state) + ', ' + city 
  end
  
  def public_events
    postings.public_posts.scheduled_events
  end
  
  def school_postings user, from = nil
    all_postings = []
    all_postings = get_school_postings user, from
    if !all_postings.nil? && !all_postings.empty?
      all_postings.sort_by!{|posting|[posting.id]}.reverse!
    end
    #all_postings.uniq!
    all_postings
  end
  
  def get_school_postings user, from = nil
    all_postings = []
    boards.each do |board|
      if from
        all_postings += board.postings.where('visibility = 1 and id > ?', from)
      else
        all_postings += board.postings.public_posts
      end
      #if user.member?(board)
      #  if from.nil?
      #  all_postings += board.postings
      #  else
      #  all_postings += board.postings.where('id > ?', from)
      #  end
      #else # current_user is not a member
      #  if from.nil?
      #  all_postings += board.postings.where(:visibility => 1)
      #  else
      #  all_postings += board.postings.where('visibility = 1 and id > ?', from)
      #  end
      #end
    end
    all_postings
  end
  
  def school_postings_on_date user, date
    all_postings = []
    all_postings = get_school_postings_on_date user, date
    if !all_postings.nil? && !all_postings.empty?
      all_postings.sort_by!{|posting|[posting.id]}.reverse!
    end
    all_postings.uniq!
    all_postings
  end

  def get_school_postings_on_date user, date
    all_postings = []
    boards.each do |board|
      all_postings += board.postings.where('visibility = 1 and created_at <= ?', date.end_of_day)
      #if user.member?(board)
      #  all_postings += board.postings.where('created_at <= ?', date.end_of_day)
      #else # current_user is not a member
      #  all_postings += board.postings.where('visibility = 1 and created_at <= ?', date.end_of_day)
      #end
    end
    all_postings
  end
  
  def get_month_events_for_date(user, date)
    # user has not been used, but it is planned to use it
    school_events = public_events
    events_arr = Array.new
    return events_arr unless school_events
    
    school_events.each do |posting|
      if future_events = posting.get_future_events_for_month(date.beginning_of_month)
        events_arr += future_events
      end
    end
    events_arr
  end

  private
    
    @cache = Hash.new
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  include ApplicationHelper
  include PostingsHelper
  
  before_filter :authenticate, :only => [:index, :show]
  before_filter :admin_user, :only => [:new, :edit, :create, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @page = valid_page_or_one params[:page]
    @title = 'Schools'
    store_location # store the page location for back functionality
    if ( params[:search].nil? && params[:state].nil? && params[:city].nil? && ( !current_user.state.nil? || !current_user.city.nil? ) )
      @schools = School.search(params[:search], current_user.state, current_user.city ).paginate(:page => @page, :per_page => per_page)
    else
      @schools = School.search(params[:search], params[:state], params[:city] ).paginate(:page => @page, :per_page => per_page) 
    end
        
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    store_location
    
    @school = School.find(params[:id])
    raise ActiveRecord::RecordNotFound if @school.nil?
    
    paginate = true
    @user = current_user
    @level_ups = Vote.level_ups.limit(20)
    
    @date = valid_date_or_today(params[:date])
    if params[:subact] != 'events_only'
      @postings = paginate_school_postings(@school, @date)
    end
    if params[:act] == 'calendar' || params[:subact] == 'events_only'
      @events = @school.get_month_events_for_date(current_user, @date)
      if params[:subact] == 'events_only' && params[:search].nil?
        day_events = posts_with_events_for_date(@events, @date)
        @postings = day_events.paginate(:page => @page, :per_page => per_page, :total_etries => day_events.size )
      end
    end

    # Autorefresh form
    @autorefresh = Posting.new
    
    if @postings.nil? || @postings.empty?
      last_post = Posting.find_by_sql("SELECT MAX(id) AS maxid FROM postings")
      @from_posting = last_post[0].maxid
    else
      @from_posting = @postings.first.id
    end
    
    # logger.debug "\n\n After postings \n\n\n"
    @title = @school.name
    
    @school_boards = @school.boards.order('created_at ASC')

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @school }
    end
    rescue ActiveRecord::RecordNotFound
      page_not_found
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_back_or home_path }
      format.js
      format.json { head :ok }
    end
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_add.html.erb
<% unless current_user.has_school?(school.id) %>
<%= form_for current_user.user_schools.build(:school_id => school.id), :class => "submitable", :remote => true do |f| %>
  <%= f.hidden_field :school_id, :value => school.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "Add", :class => "button_confirm" %>
<% end %>
<% end %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.select(:state, State.all) %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit 'Save', :class => "save_button" %>
  </div>
<% end %>

app/views/schools/_remove_school.html.erb
<%= button_to 'Remove', current_user.user_schools.find_by_school_id(school.id),
    :class => "button_reject tips", :disable_with => 'Deleting...',
    confirm: "Do you want to unlink \"#{school.name}\" from your profile?", 
    method: :delete, :remote => true,
    :title => "Unlink #{school.name} from your profile" 
%>

app/views/schools/_school_boards.html.erb
<div class="background_write_2">School Boards</div>
<%
  if params[:school_id]
  	@school = School.find_board(params[:school_id])
    @school_boards = @school.boards.order('created_at ASC') if @school
  end
%>
<%= render 'shared/containers/small_container', :container => @school_boards, :action => '' %>

app/views/schools/_school_details.html.erb
<div id="school_details">
<%= link_to @school.name, @school.url, :confirm => "You will be redirected to the #{@school.name} website as we found it on name.com.\nThe URL of the website: #{@school.url}.\nAre you sure?" %>
<br />
<%= link_to @school.location, @school.url, :confirm => "You will be redirected to the #{@school.name} website as we found it on name.com.\nThe URL of the website: #{@school.url}.\nAre you sure?" %>
</div>

 

app/views/schools/_tab_add_school.html.erb
<% if current_user.has_school?(@school.id) %>
<b>This school is already linked to your profile.</b>
<% else %>
Linking a school to your profile will allow you to recieve public posts from the boards that linked to that school.<br />
Whould you like to add this school to your profile?<br /><br /> 
<%= render 'user_schools/btn_add_school', :school => @school %>
<% end %>

app/views/schools/_title.html.erb
<div id="title_top_nav" class="clickable">
<%= render 'schools/title_top_nav' %>
</div>

app/views/schools/_title_main_menu.html.erb
<!-- SECOND LEVEL SERVICE BUTTONS -->
<div id="second_level_btns">
<!-- %= render 'home/second_level_btns' % -->
</div> <!-- end of second_level_btns -->
<!-- END OF SECOND LEVEL SERVICE BUTTONS -->

<!-- FIRST LEVEL SERVICE BUTTONS -->
<div class="first_menu_button <%= selected_if(params[:act] == 'calendar') %>">
<%= link_to 'CALENDAR', school_path(@school)+'?act=calendar', :class => 'tips', :title => "Show event calendar", :disable_with => "Loading..." %>
</div>

<div class="second_menu_button <%= selected_if(params[:act] == 'add_school') %>">
<%= link_to 'ADD', school_path(@school)+'?act=add_school', :class => 'tips', :title => "Add school to your profile", :disable_with => "Loading..." %>
</div>

app/views/schools/_title_top_action.html.erb
<% if !params[:act].nil? %>

	<% if params[:act] == 'add_school' %>
	<div class="tab_add_school"><%= render 'schools/tab_add_school' %></div>
	<% elsif params[:act] == 'calendar' %>
	<div class="action_tab"><%= render 'schools/tab_calendar' %></div>
	<% end %>
<% elsif params[:subact] == 'events_only' %>
    <div class="action_tab"><%= render 'schools/tab_calendar' %></div>
    
<% end %>

app/views/schools/_title_top_nav.html.erb
<div id="menu_buttons">
<% unless current_user.nil? %>

<div id="main_menu">
<!-- FIRST LEVEL BUTTONS -->
<%= render 'schools/title_main_menu' %>
</div> <!-- end of main_menu div -->

<!-- OPTIONAL BUTTONS -->
<div id="optional_buttons">
<%= render 'schools/school_details' %>
</div>

<% end %>
</div>

app/views/schools/destroy.js.erb
<% if stored_location_or_home =~ /\/home?/ %>
$("#user_schools").html("<%= escape_javascript(render 'home/user_schools', :user => current_user ) %>");
$("#title_top_action").html("");
$(".sub_title_nav").html("<%= escape_javascript(render 'home/sub_title_nav') %>");
	<% if current_user.schools.count <= max_num_schools %>
	$("#title_print_schools").html("<%= escape_javascript( render 'home/title_print_schools' ) %>");
	<% end %>
<% end %>

<% if flash.any? || !notice.nil? %>
$(".info_note").html("<%= escape_javascript(render 'home/info') %>");
<% end %>
$(".loading").html("");
$(".tips").tipTip();


app/views/schools/index.html.erb
<div id="schools_content">

<%= link_to 'New School', new_school_path, :class => "button_neutral float_right" %>

<div id="user_postings">
<%= render 'shared/school_search', :search_path => schools_path %>
</div>

<%= link_to 'Back', :back, :class => "button_neutral" %>

</div>

app/views/schools/new.html.erb
<div id="schools_content">
<h1>New school</h1>
<%= link_to 'Back', :back, :class => "button_neutral" %>
<br />
<%= render 'form' %>


</div>

app/views/schools/show.js.erb
<% if !params[:page].nil? %>
    $("#user_postings").html("<%= escape_javascript(render 'shared/containers/page_container', :page_container => @postings) %>");

<% elsif params[:act] == 'cancel' %>
    $("#title_top_action").html("");
    $("#main_menu").html("<%= escape_javascript(render 'schools/title_main_menu') %>");
    
<% elsif params[:subact] == 'events_only' %>
    $("#title_top_action").html("<%= escape_javascript(render 'schools/tab_calendar') %>");
    $("#user_postings").html("<%= escape_javascript(render 'schools/school_postings') %>");
    document.title = "School Events";
    
<% elsif !params[:act].nil? %>
        
    <% if params[:act] == 'messages' %>
        $("#title_top_action").html("");
        $(".home_sub_title").html("<%= escape_javascript(render 'home/home_sub_title') %>");
        $("#user_postings").html("<%= escape_javascript(render 'home/messages') %>");
        document.title = "My Messages";
        
    <% elsif params[:act] == 'add_school' %>
        $("#title_top_action").html("<%= escape_javascript(render 'schools/tab_add_school') %>");
        $("#main_menu").html("<%= escape_javascript(render 'schools/title_main_menu') %>");
        document.title = "Add school";

    <% elsif params[:act] == 'calendar' %>
        $(".home_sub_title").html("<%= escape_javascript(render 'home/home_sub_title') %>");
    	$("#main_menu").html("<%= escape_javascript(render 'schools/title_main_menu') %>");
        $("#title_top_action").html("<%= escape_javascript(render 'schools/tab_calendar') %>");
        $("#user_postings").html("<%= escape_javascript(render 'schools/school_postings') %>");
        document.title = "School Calendar";
    <% end %>

<% else %>
   $("#title_top_action").html("");
   $("#main_menu").html("<%= escape_javascript(render 'schools/title_main_menu') %>");
   $("#user_postings").html("<%= escape_javascript(render 'schools/school_postings') %>");
<% end %>

$(".logo_messages").html("<%= escape_javascript( render 'home/check_new_msg' ) %>");
$(".info_note").html("<%= escape_javascript(render 'home/info') %>");
$(".loading").html("");
$(".tips").tipTip();